/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EmDasherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var EmDasherPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.handleEditorChange = (editor, markdownView) => {
      const cursorPos = editor.getCursor();
      const line = editor.getLine(cursorPos.line);
      if (cursorPos.ch < 3) {
        return;
      }
      const charJustTyped = line.charAt(cursorPos.ch - 1);
      const twoCharsBefore = line.substring(cursorPos.ch - 3, cursorPos.ch - 1);
      if (charJustTyped === " ") {
        if (twoCharsBefore === "--") {
          const charBeforePairIndex = cursorPos.ch - 4;
          if (charBeforePairIndex < 0 || line.charAt(charBeforePairIndex) !== "-") {
            const contextCheckPos = {
              line: cursorPos.line,
              ch: cursorPos.ch - 1
            };
            const textContextBeforeDash = line.substring(0, cursorPos.ch - 3);
            const contextPosBeforeDash = {
              line: cursorPos.line,
              ch: cursorPos.ch - 3
            };
            if (!this.isInsideCodeBlock(editor, contextCheckPos) && !this.isInsideUrl(
              textContextBeforeDash,
              editor,
              contextPosBeforeDash
            )) {
              editor.replaceRange(
                "\u2014",
                // Replace with em-dash
                { line: cursorPos.line, ch: cursorPos.ch - 3 },
                // Start of "--"
                { line: cursorPos.line, ch: cursorPos.ch - 1 }
                // End of "--"
              );
            }
          }
        }
      }
    };
  }
  async onload() {
    this.app.workspace.on("editor-change", this.handleEditorChange);
  }
  async onunload() {
    this.app.workspace.off("editor-change", this.handleEditorChange);
  }
  isInsideCodeBlock(editor, cursorPos) {
    const cmEditor = editor.cm;
    if (!cmEditor || !cmEditor.getModeAt)
      return false;
    for (let i = Math.max(0, cursorPos.line - 10); i <= cursorPos.line; i++) {
      const lineText = editor.getLine(i);
      if (lineText.trim().startsWith("```")) {
        let inBlock = false;
        for (let j = 0; j <= cursorPos.line; j++) {
          if (editor.getLine(j).trim().startsWith("```"))
            inBlock = !inBlock;
        }
        if (inBlock || editor.getLine(cursorPos.line).trim().startsWith("```") && cursorPos.ch > editor.getLine(cursorPos.line).indexOf("```")) {
          for (let k = cursorPos.line; k < editor.lineCount(); k++) {
            if (editor.getLine(k).includes("```", k === cursorPos.line ? cursorPos.ch : 0))
              return true;
          }
          if (inBlock)
            return true;
        }
      }
    }
    const token = cmEditor.getTokenAt(cursorPos, true);
    if (token && token.type && token.type.includes("code") && token.type.includes("inline")) {
      const lineContent = editor.getLine(cursorPos.line);
      const dashStartIndex = cursorPos.ch - 2;
      if (dashStartIndex >= token.start && cursorPos.ch <= token.end) {
        if (lineContent.substring(token.start, token.end).includes("--")) {
          return true;
        }
      }
    }
    const currentLine = editor.getLine(cursorPos.line);
    let backtickCount = 0;
    for (let i = 0; i < cursorPos.ch - 2; i++) {
      if (currentLine[i] === "`") {
        backtickCount++;
      }
    }
    if (backtickCount % 2 !== 0) {
      if (currentLine.substring(cursorPos.ch).includes("`")) {
        return true;
      }
    }
    return false;
  }
  isInsideUrl(textBeforeDash, editor, cursorPos) {
    const currentLine = editor.getLine(cursorPos.line);
    const textAfterDash = currentLine.substring(cursorPos.ch);
    const fullPotentialUrl = textBeforeDash + "--" + textAfterDash.split(/[\s()\[\]]/)[0];
    const urlPattern = /((?:https?|ftp):\/\/(?:[\w\-]+\.)+[\w\-]+(?:[\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?)/i;
    if (urlPattern.test(fullPotentialUrl)) {
      const match = fullPotentialUrl.match(urlPattern);
      if (match && match[0].includes("--")) {
        const urlStartIndex = currentLine.indexOf(match[0]);
        if (urlStartIndex === -1)
          return false;
        const urlEndIndex = urlStartIndex + match[0].length;
        if (cursorPos.ch > urlStartIndex && cursorPos.ch <= urlEndIndex) {
          const partOfUrlBeforeCursor = match[0].substring(
            0,
            cursorPos.ch - urlStartIndex - 2
          );
          const hostAndPath = match[0].replace(/^((?:https?|ftp):\/\/)/i, "");
          const host = hostAndPath.split("/")[0];
          if (host.includes("--")) {
            const potentialHostPartInLine = textBeforeDash.substring(
              textBeforeDash.toLowerCase().indexOf(host.toLowerCase())
            );
            if (potentialHostPartInLine.length <= host.length) {
              return true;
            }
          }
          return true;
        }
      }
    }
    return false;
  }
};
